# Generated by Django 5.1 on 2024-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_comentario_usuario_producto_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagen",
            name="url",
            field=models.ImageField(
                upload_to="imagenes_de_productos/", verbose_name="Imagen"
            ),
        ),
    ]
