# Generated by Django 5.1 on 2024-09-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_imagen_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagenes",
        ),
        migrations.AddField(
            model_name="imagen",
            name="productos",
            field=models.ManyToManyField(
                blank=True, related_name="imagenes_inversas", to="product.producto"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="imag",
            field=models.ManyToManyField(
                related_name="productos_inversos",
                to="product.imagen",
                verbose_name="Imágenes",
            ),
        ),
    ]
