# Generated by Django 5.1 on 2024-09-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_producto_imagenes_imagen_productos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imag",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagenes",
            field=models.ManyToManyField(
                related_name="productos_inversos",
                to="product.imagen",
                verbose_name="Imágenes",
            ),
        ),
    ]
