# Generated by Django 5.1 on 2024-09-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_imagenes_producto_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="image",
            new_name="imagenes",
        ),
    ]
