# Generated by Django 5.1 on 2024-09-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_rename_image_producto_imagenes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagenes",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos_inversos",
                to="product.imagen",
                verbose_name="Imágenes",
            ),
        ),
    ]
