# Generated by Django 5.1 on 2024-09-23 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_producto_imagenes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="calificaciones",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Calificación",
            ),
        ),
    ]
