# Generated by Django 5.1 on 2024-09-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_producto_calificaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="trafico",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=2,
                max_length=255,
                null=True,
                verbose_name="Tráfico",
            ),
        ),
    ]
