# Generated by Django 5.1 on 2024-09-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_producto_trafico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="areas_uso",
            field=models.TextField(blank=True, null=True, verbose_name="Áreas de uso"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="calidad",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Calidad"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="componentes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Componentes incluidos"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="contenido_producto",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido del producto"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="dilucion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dilución"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="dimensiones",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dimensiones"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="forma",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Forma"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="formato",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Formato"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="garantia",
            field=models.TextField(blank=True, null=True, verbose_name="Garantía"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="incluye",
            field=models.TextField(blank=True, null=True, verbose_name="Incluye"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="lavabilidad",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lavabilidad"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="materiales",
            field=models.TextField(blank=True, null=True, verbose_name="Materiales"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="no_incluye",
            field=models.TextField(blank=True, null=True, verbose_name="No incluye"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="perfil_tasa",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Perfil de tasa"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="presentacion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Presentación"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="productos_compatibles",
            field=models.TextField(
                blank=True, null=True, verbose_name="Productos compatibles"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sistema_accionamiento",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sistema de accionamiento",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sistema_descarga",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sistema de descarga",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_asiento",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de asiento"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_chorro",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de chorro"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_cierre",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de cierre"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_griferia",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de grifería"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_herrajes",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de herrajes"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_instalacion",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Tipo de instalación",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_lavamanos",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de lavamanos"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_manija",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de manija"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_mezclador",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de mezclador"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_pintura",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de pintura"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_regadera",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de regadera"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_sifon",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de sifón"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo_tanque",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de tanque"
            ),
        ),
    ]
