# Generated by Django 5.1 on 2024-09-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_producto_areas_uso_alter_producto_calidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="rendimiento",
            field=models.TextField(blank=True, null=True, verbose_name="Rendimiento"),
        ),
    ]
