# Generated by Django 5.1 on 2024-09-24 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_producto_rendimiento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="calificaciones",
        ),
        migrations.AddField(
            model_name="comentario",
            name="calificacion",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Calificación",
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
            preserve_default=False,
        ),
    ]
