# Generated by Django 5.1 on 2024-09-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_remove_producto_calificaciones_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="comentarios",
        ),
        migrations.AddField(
            model_name="comentario",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="product.producto",
                verbose_name="Producto",
            ),
        ),
    ]
