# Generated by Django 5.1 on 2024-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_remove_producto_comentarios_comentario_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="approved_comment",
            field=models.BooleanField(default=False),
        ),
    ]
