# Generated by Django 5.1.1 on 2024-09-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoppingcart', '0002_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orderNumber', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('shoppingCart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.carrito')),
            ],
        ),
    ]
