# Generated by Django 5.1.1 on 2024-09-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orden_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='orderNumber',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
