# Generated by Django 5.1 on 2024-09-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_orden_ordernumber"),
        ("shoppingcart", "0002_itemcarrito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="shoppingCart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shoppingcart.carrito"
            ),
        ),
    ]
