# Generated by Django 4.1 on 2024-11-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orden_shoppingcart'),
        ('order', '0005_remove_orden_shoppingcart_ordenproducto_and_more'),
    ]

    operations = [
    ]
